### PR TITLE
Ajout "PARALLEL BUILDS WEBHOOK" (2ème essai)

### PR DESCRIPTION
**Pull request by A-312**
I retry this feature of coveralls for : https://github.com/lemurheavy/coveralls-public/issues/1362#issuecomment-610073774

### CODE REVIEW

**Comment by nickmerwin** [comment]
@A-312 ok, the build completed successfully and the coverage comment was sent, but the `Fail` status wasn't added because the user that owns the repo on Coveralls, @Taluu, does not have write permissions on _this_ repo.

To solve for that, we could give this repo ownership over to you or another collaborator, or @Taluu could be added to it here.

**Comment by A-312** [comment]
I don't understand what I have to do, have I to ask owners of zds-site to use marketplace and add corveralls ?

**Comment by A-312** [comment]
Should be done for permission to Taluu, I rerun travis: https://travis-ci.com/github/zestedesavoir/zds-site/builds/159196064

**Comment by A-312** [comment]
@artragis Seems to be not good :-/ @nickmerwin Add coveralls with marketplace, can fix it ?

**Comment by Situphen** [comment]
@nickmerwin When you talk about the "Fail status", you mean this ?

image

As for the repo ownership, if you could transfer it to @artragis or to me, it would be perfect. @Taluu is no longer an active developer of `zds-site`.

**Comment by nickmerwin** [comment]
Hi @Situphen, I've assigned the repo ownership on Coveralls to you.

Re: Fail status, yes, it would show up there as a 2nd check.

Can you please trigger another build to confirm?

**Comment by nickmerwin** [comment]
image

Confirmed the status came through on that last build.

Looks like it's all good to go now!

**Comment by A-312** [comment]
Thanks you !

**Pull request merged**
